# This is a basic workflow to help you get started with Actions

name: nike_scheduler

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: crawler request
        id: nike
        uses: fjogeleit/http-request-action@v1
        with:
            url: 'http://13.125.234.52:8080/api/crawl/nike'
            method: 'GET'
      - name: Show Response
        run: echo ${{ steps.nike.outputs.response }}
